[project]
protostar-version = "0.9.1"
lib-path = "lib"

[contracts]
operators = ["src/onnx_cairo/tensor_operations.cairo"]
utils = ["src/onnx_cairo/tensor_utils.cairo"]
data_types = ["src/onnx_cairo/tensor_data_types.cairo"]

# Command Configuration
[test]
target = ["src"]

[format]
target = ["src", "tests"]
ignore-broken = true

[profile.testnet.project]
network = "testnet"